### ISSUE TITLE
Missing events received before accepting room invite

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-x-ios#1240]
### Steps to reproduce

1. Alice creates an e2ee room
2. Alice sends three messages
3. Bob accepts the invite
4. Alice sends another message

#### What did you expect?

For Bob to see four messages

#### What happened instead?

Bob only saw the last message that Alice sent, the one sent after he accepted the room invite

### Your phone model

iPhone 13

### Operating system version

iOS 16

### Application version

1.1.6 (267)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
Issue for this is in the SDK here: https://github.com/matrix-org/matrix-rust-sdk/issues/2302

**Comment by ara4n** [comment]
this just bit me really badly; it's a horrible flaky bug.

**Comment by ara4n** [comment]
worse, it looks like everything you then send into the newly joined room is UTD

**Comment by ara4n** [comment]
To add insult to injury, it briefly flashes up the messages in the timeline before then hiding them again on accepting an invite. There's also some other pattern happening where they sometimes reappear on launch, but sometimes don't.

**Comment by Hywan** [comment]
Just tested and things are fixed.

**Comment by 9p4** [comment]
I'm the user in the screenshot above.

- iOS 17.5 (iPhone 13 Mini)
- Element X iOS 1.6.7

Let me know if you need any more information.

**Comment by stefanceriu** [comment]
Ivan is right, this is no longer an issue.

**Comment by ara4n** [comment]
i am very sure this is still an issue - i saw it happen on amandine's account last week. we just don't have the right repro steps yet. let's continue this at https://github.com/element-hq/element-x-ios/issues/2024
