### ISSUE TITLE
Room timelines can sometimes get stuck

### ISSUE THREAD

**Issue by Kimiblock** [element-hq/element-x-ios#2914]
### Steps to reproduce

1. Open the app
2. Navigate for a while
3. Send a message and realize the timeline has been frozen

#### What did you expect?

Working timeline

#### What happened instead?

Frozen timeline

### Your phone model

iPhone 13

### Operating system version

iOS 17

### Application version

Version: 1.6.8 (107)

### Homeserver

moechat.kimiblock.top Synapse 1.110.0rc1

### Will you send logs?

Yes

**Comment by Kimiblock** [comment]
Indeed better, though slowdowns when opening the room still happens


--
Sincerely, 
Kimiblock

**Comment by stefanceriu** [comment]
Thanks for checking. Loading initial items on opening rooms has been addressed [here](https://github.com/matrix-org/matrix-rust-sdk/pull/35350) and deadlocks have been fixed so I will close this issue.

**Comment by Kimiblock** [comment]
> Thanks for checking. Loading initial items on opening rooms has been addressed [here](https://github.com/matrix-org/matrix-rust-sdk/pull/35350) and deadlocks have been fixed so I will close this issue.

Is that a dead link?

**Comment by stefanceriu** [comment]
Oh sorry, I had a typo, edited now.

**Comment by Kimiblock** [comment]
https://github.com/element-hq/element-x-ios/assets/61745317/68cef0bb-c493-4203-99b3-68dfd6c74476

It still occurs to me, 1.6.11

**Comment by mblackshaw** [comment]
We're seeing this super often on 1.6.9 too.

**Comment by pixlwave** [comment]
> RPReplay_Final1718812948.mp4 
> 
> It still occurs to me, 1.6.11
> 
> Maybe I should reopen this

In this video, if you were to have waited longer would the message have appeared in the timeline? If that's true, next it this happens could you add a screenshot which includes the scroll bar?

I believe this might be an instance of the timeline having far too many items loaded (given how long it takes to open the room again) so simply being slow. One trigger for this was fixed in #2969 although there's still another potential way this can happen (albeit more slowly).

**Comment by Kimiblock** [comment]
Will try. I’m a little sick recently.


--
Sincerely, 
Kimiblock

**Comment by mblackshaw** [comment]
FWIW this has been much better with 1.6.11. I don't think I've seen it once.

**Comment by Kimiblock** [comment]
Seen this again

![IMG_7792](https://github.com/element-hq/element-x-ios/assets/61745317/4008db84-0471-4320-8861-74675def73a8)

**Comment by ara4n** [comment]
i haven't seen this in forever.
